"""Verify a draft's prose against the provisions actually retrieved for it.

``draft.citations_of()`` already guarantees the citation list: every pinpoint
under BASED ON came from a row retrieval returned. Nothing guaranteed the
*prose*. A clause could state a notice period of four weeks, cite s 117, and
be cited correctly while saying something s 117 does not say. Until now the
only thing standing between that and a practitioner was a human reading it.

This module closes that gap in three steps, two of which are code:

1. :func:`split_claims` - deterministic. Cut the draft into atomic claims and
   drop everything that asserts nothing: headings, rules, label lines, the
   generated scaffolding, the closing blocks, and any sentence carrying an
   unsupplied value.
2. :func:`build_prompt` and the :data:`JudgeFn` behind it - the only model
   call. A judge in a *different model family* from the drafting model is
   given the claims and the verbatim text of the retrieved provisions, and
   nothing else, and must answer in strict JSON.
3. :func:`validate_verdicts` - deterministic again, and the part that carries
   the guarantee. Every way the judge can fail - unparseable output, a missing
   claim, an invented verdict word, a provision id that is not in the
   retrieved set, a timeout, an unreachable provider, a same-family
   misconfiguration - resolves to UNSUPPORTED. There is no path through this
   module that turns a failure into a SUPPORTED claim.

Two things this module never does. It never rewrites the draft: annotation is
insertion only, at character offsets recorded during the split, so no drafted
word can be lost. And it never consults anything but the provisions handed to
it - no web, no second retrieval, no model memory. A judge asked "is this
supported" with access to its own recollection of the Fair Work Act will
confirm a claim the corpus does not hold, which is precisely the failure this
exists to catch.

A note for the phase that adds case law. Every unit-of-text decision here is
behind :class:`ClaimUnit`; ``SENTENCE`` is the only one registered today. A
paragraph unit registers itself beside it and nothing else in this file, in
``draft.py`` or in ``tools.py`` changes.
"""

from __future__ import annotations

import json
import re
import time
from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass, field, replace
from typing import Any, Literal, Protocol

import httpx

from michael.config import ConfigError, settings
from michael.draft import MISSING_RE, Draft
from michael.retrieve import RetrievedProvision

Verdict = Literal["SUPPORTED", "PARTIAL", "UNSUPPORTED"]

#: The only three words a judge may answer with. Anything else - "PARTIALLY",
#: "supported", "YES" - is not one of these and is therefore a failure, which
#: resolves to UNSUPPORTED. Accepting near-misses would mean guessing what the
#: judge meant, and a guess is the thing this module exists to remove.
VERDICTS: tuple[Verdict, ...] = ("SUPPORTED", "PARTIAL", "UNSUPPORTED")

#: Verdicts that put the claim in front of a human.
FLAGGED: frozenset[str] = frozenset({"PARTIAL", "UNSUPPORTED"})

#: Headings that ``draft.py`` appends after the drafted body. Everything from
#: the first of these onwards is generated by code and is not prose anyone
#: needs checked against a provision - the citation list is already guaranteed
#: by ``citations_of``, and the closing blocks are fixed text.
TRAILING_HEADINGS = (
    "## BASED ON",
    "## VERIFICATION",
    "## OPEN ITEMS",
    "## VERIFY BEFORE USE",
)

MIN_CLAIM_WORDS = 5
"""Below this a fragment is a label, a heading remnant or a stub, not an
assertion about the law. Set low on purpose: "The notice period is 5 weeks"
is six words and is exactly the kind of wrong number that must be caught, so
the floor has to sit under it rather than at a comfortable prose length."""

_SENTENCE_END = re.compile(r"(?<=[.!?])(?=\s)")

_HEADING = re.compile(r"^\s*#{1,6}\s")
_RULE = re.compile(r"^\s*(?:-{3,}|\*{3,}|_{3,})\s*$")
_BOLD_FIELD = re.compile(r"^\s*\*\*[^*]+:\*\*")
"""The template's party-field convention: ``**Employer:** Acme Pty Ltd of ...``
That is an identification, not a claim about the law, and it is the one line
shape in the corpus of templates that reliably carries a party name."""

_LIST_MARKER = re.compile(r"^\s*(?:[-*+]|\d+[.)])\s+")

_GENERATED_LINE = re.compile(
    r"^[ \t]*(?:"
    # The metadata header and the clause skeleton that
    # draft.outline_without_template() writes.
    r"(?:Request|Domain):\s"
    r"|No template in templates/"
    r"|The outline below is"
    r"|No provisions were retrieved for this request"
    r"|-\s*(?:Party [AB]|Commencement"
    r"|Nearest retrieved provision|Operative words|Source"
    r"|Clause to be drafted)\b"
    r")",
    re.MULTILINE,
)
"""Whole lines that ``draft.py`` writes itself, matched by their literal text.

These are excluded unconditionally, without the statutory-reference guard
below, and that is the difference between them and template prose: code wrote
them, so code knows they assert nothing. The outline's "Nearest retrieved
provision" line names an Act in every case - the guard would keep every one of
them - and yet it asserts nothing a judge could rule on. The pinpoint it
carries is already guaranteed by ``draft.citations_of``, and the quote beside
it by ``output_check.citation_fidelity``.

They are blanked rather than deleted (see :func:`_verifiable_body`) so the
character offsets annotation writes back to stay exact."""

_DOCUMENT_SUBJECT = re.compile(
    r"^(?:"
    # Savings and entire-agreement clauses, and the compliance disclaimer
    # MICHAEL.md requires. These assert something about this document, not
    # about the law, so no provision can support or contradict them.
    r"nothing in (?:this|the) (?:document|contract|agreement|outline|draft)\b"
    r"|(?:this|the) (?:document|contract|agreement|outline|draft|template)\b"
    r")",
    re.IGNORECASE,
)
"""A sentence of *template prose* whose subject is the artefact, not the law.

Narrow by construction, and guarded by :data:`_LEGAL_REFERENCE` below: the
failure direction that matters is excluding a claim that should have been
checked, so a sentence that looks self-referential but names a statute is
kept and judged anyway. Unlike :data:`_GENERATED_LINE` this is a shape rule
applied to prose nobody in this repository wrote, so it errs open."""

_LEGAL_REFERENCE = re.compile(
    r"\bAct\b|\bRegulations?\b|\bAward\b|\bNational Employment Standards\b"
    r"|\bs\.?\s?\d|\bsection\s+\d|\bSch(?:edule)?\.?\s*\d",
    re.IGNORECASE,
)
"""Enough of a statutory reference to override :data:`_DOCUMENT_SUBJECT`.

The casual contract template opens "This contract is drafted on the basis
that ... the Fair Work Act 2009 (Cth), the National Employment Standards and
the applicable Modern Award govern the employment". Its subject is the
contract; its content is a claim about which law applies, and the judge must
see it."""


class ClaimUnit(Protocol):
    """How a body of drafted text is cut into the things a judge rules on.

    The seam the case-law phase needs. A judgment is not cut into sentences -
    a holding runs across several and a numbered paragraph is the unit a court
    is cited by - so that phase registers a paragraph unit here. Nothing else
    in this module knows what a unit is: :class:`Claim` records which one
    produced it, and the judge prompt names it, so two unit types can coexist
    in one draft without either being special-cased.
    """

    @property
    def name(self) -> str:
        """What to call this unit in the judge prompt - "sentence"."""

    def split(self, text: str) -> list[tuple[int, int]]:
        """Character spans of ``text``, in order, one per candidate claim."""


@dataclass(frozen=True, slots=True)
class SentenceUnit:
    """One sentence, in a paragraph that has been unwrapped first.

    Templates are hard-wrapped, so a sentence routinely spans three source
    lines. Splitting on lines would cut claims in half and hand the judge
    fragments; splitting the *unwrapped* paragraph and mapping back to the
    original offsets keeps the spans usable for annotation.
    """

    name: str = "sentence"

    def split(self, text: str) -> list[tuple[int, int]]:
        spans: list[tuple[int, int]] = []
        for start, end in _paragraph_spans(text):
            block = text[start:end]
            cursor = 0
            for piece in _SENTENCE_END.split(block):
                if piece.strip():
                    lead = len(piece) - len(piece.lstrip())
                    spans.append((start + cursor + lead, start + cursor + len(piece.rstrip())))
                cursor += len(piece)
        return spans


SENTENCE: ClaimUnit = SentenceUnit()

#: Registered unit types, by name. The case-law phase adds "paragraph" here.
UNITS: dict[str, ClaimUnit] = {SENTENCE.name: SENTENCE}


def _paragraph_spans(text: str) -> list[tuple[int, int]]:
    """Spans of blank-line separated blocks, skipping blocks that are not prose."""
    spans: list[tuple[int, int]] = []
    offset = 0
    for block in re.split(r"\n[ \t]*\n", text):
        start, end = offset, offset + len(block)
        offset = end + 2  # the separator is at least "\n\n"; see _fix_offsets
        if block.strip():
            spans.append((start, end))
    return _fix_offsets(text, spans)


def _fix_offsets(text: str, spans: list[tuple[int, int]]) -> list[tuple[int, int]]:
    """Re-anchor spans by searching forward, so a wider separator cannot shift them.

    ``re.split`` discards the separator and a blank line may carry trailing
    spaces, so arithmetic on the split pieces drifts. Annotation inserts at
    these offsets, and an offset that drifts inserts a marker into the middle
    of a word, so they are re-found in the source rather than computed.
    """
    fixed: list[tuple[int, int]] = []
    cursor = 0
    for start, end in spans:
        block = text[start:end]
        found = text.find(block, cursor)
        if found < 0:  # pragma: no cover - only reachable if text mutated
            found = start
        fixed.append((found, found + len(block)))
        cursor = found + len(block)
    return fixed


@dataclass(frozen=True, slots=True)
class Claim:
    """One atomic assertion from the draft, with where it sits in the text."""

    claim_id: str
    text: str
    start: int
    end: int
    unit: str = SENTENCE.name


@dataclass(frozen=True, slots=True)
class Ruling:
    """One validated verdict. Only ever produced by :func:`validate_verdicts`."""

    claim_id: str
    verdict: Verdict
    provision_ids: tuple[str, ...]
    reason: str

    @property
    def flagged(self) -> bool:
        return self.verdict in FLAGGED


@dataclass(frozen=True, slots=True)
class JudgeCall:
    """What one judge call cost, so the price of verification is reportable."""

    model: str
    seconds: float
    prompt_tokens: int = 0
    completion_tokens: int = 0
    cost_usd: float | None = None
    error: str = ""


@dataclass(frozen=True, slots=True)
class Verification:
    """The outcome of verifying one draft."""

    claims: tuple[Claim, ...]
    rulings: tuple[Ruling, ...]
    judge_model: str
    skipped_unsupplied: int = 0
    call: JudgeCall | None = None
    notes: tuple[str, ...] = field(default_factory=tuple)

    @property
    def counts(self) -> dict[str, int]:
        tally: dict[str, int] = dict.fromkeys(VERDICTS, 0)
        for ruling in self.rulings:
            tally[ruling.verdict] += 1
        return tally

    @property
    def flagged(self) -> tuple[Ruling, ...]:
        return tuple(r for r in self.rulings if r.flagged)

    def claim(self, claim_id: str) -> Claim | None:
        return next((c for c in self.claims if c.claim_id == claim_id), None)


class JudgeError(RuntimeError):
    """The judge could not be reached, or returned something unusable.

    Never raised out of :func:`verify_draft`: it is caught there and turned
    into an UNSUPPORTED verdict on every claim. It exists so the *reason* for
    failing closed reaches the practitioner instead of being swallowed.
    """


#: The judge seam. Takes the assembled prompt, returns the raw response body
#: and what the call cost. Injected in tests; defaults to OpenRouter.
JudgeFn = Callable[[str], tuple[str, JudgeCall]]


# --- step 1: split the draft into claims (code) ----------------------------


def _verifiable_body(text: str) -> str:
    """The drafted prose, with everything code generated taken out of it.

    Two removals. The trailing blocks - the citation list and the closing
    blocks - are cut off at the first heading that starts them. The outline's
    own scaffolding lines are *blanked*, not deleted: every character index in
    what comes back still points at the same character of the original, so
    :func:`annotate` can write a marker at a claim's end offset and land in
    the right place.
    """
    cut = len(text)
    for heading in TRAILING_HEADINGS:
        found = text.find(f"\n{heading}")
        if found >= 0:
            cut = min(cut, found)
    body = text[:cut]
    return "\n".join(
        " " * len(line) if _GENERATED_LINE.match(line) else line for line in body.split("\n")
    )


def _is_claim(sentence: str) -> bool:
    """Does this fragment assert something a provision could support?"""
    stripped = sentence.strip()
    if not stripped:
        return False
    if _HEADING.match(stripped) or _RULE.match(stripped):
        return False
    if _BOLD_FIELD.match(stripped) and not stripped.rstrip().endswith("."):
        return False
    if stripped.rstrip().endswith(":"):
        # A label introducing a block - "Signed by the Employee:" - asserts
        # nothing on its own.
        return False
    naked = _LIST_MARKER.sub("", stripped)
    if _DOCUMENT_SUBJECT.match(naked) and not _LEGAL_REFERENCE.search(naked):
        return False
    return len(re.findall(r"[A-Za-z][\w'-]*", naked)) >= MIN_CLAIM_WORDS


def split_claims(draft_text: str, *, unit: ClaimUnit = SENTENCE) -> tuple[tuple[Claim, ...], int]:
    """Cut a draft into atomic claims. Returns the claims and how many were skipped.

    A sentence carrying a ``[MISSING: ...]`` marker is skipped rather than
    judged. Its operative value was never supplied, so there is nothing for a
    provision to support, and it is already in front of the practitioner under
    OPEN ITEMS. The count comes back so the VERIFICATION section can say how
    many were set aside - a skip that is not reported is a silent one, and
    this module does not have silent ones.
    """
    body = _verifiable_body(draft_text or "")
    claims: list[Claim] = []
    skipped = 0
    for start, end in unit.split(body):
        sentence = body[start:end]
        if not _is_claim(sentence):
            continue
        if MISSING_RE.search(sentence):
            skipped += 1
            continue
        claims.append(
            Claim(
                claim_id=f"c{len(claims) + 1}",
                text=" ".join(sentence.split()),
                start=start,
                end=end,
                unit=unit.name,
            )
        )
    return tuple(claims), skipped


# --- step 2: ask the judge (the only model call) ---------------------------


def provision_id_of(provision: RetrievedProvision) -> str:
    """The id the judge cites a provision by.

    A string, not the database integer, because the case-law phase adds units
    with their own id space ("paragraph 47 of judgment 12") and a membership
    check that only understands integers would have to be rewritten for it.
    """
    return str(provision.provision_id)


JUDGE_INSTRUCTIONS = """\
You are verifying a draft legal document against the ONLY evidence available.

The PROVISIONS below are the complete and exclusive evidence. You have no other
source. Do not use your own knowledge of Australian law, of the Fair Work Act,
of any award, or of anything else. If a claim is true in the real world but the
provisions below do not say it, it is UNSUPPORTED. That is the point of this
task: a claim the provisions do not carry must be reported, however correct it
may be.

For EVERY claim you must return one object:
  {"claim_id": "<exact id>", "verdict": "SUPPORTED"|"PARTIAL"|"UNSUPPORTED",
   "provision_ids": ["<id>", ...], "reason": "<one sentence>"}

  SUPPORTED   - the provision text states this, including every number, party,
                condition and qualifier in the claim.
  PARTIAL     - the provisions carry part of it: the substance is there but a
                number, a party, a scope or a qualifier differs or is absent.
  UNSUPPORTED - nothing in the provisions carries it.

Rules:
- provision_ids must name provisions from the list below, by their exact id.
  Never invent an id. If you cannot name one, the verdict is UNSUPPORTED and
  provision_ids is [].
- SUPPORTED and PARTIAL require at least one provision_id.
- A claim that names an obligation of the wrong party, a number the provisions
  do not state, an exception the provisions do not create, or a scope wider
  than the provisions grant, is not SUPPORTED.
- Return one object per claim, for every claim, and nothing else.

Answer with a single JSON object and no other text:
{"verdicts": [ ... ]}"""


def build_prompt(claims: Sequence[Claim], provisions: Sequence[RetrievedProvision]) -> str:
    """Assemble the judge prompt from the claims and the retrieved text only.

    The provision text is verbatim from retrieval. It is capped per provision
    at ``VERIFY_PROVISION_MAX_CHARS`` because a Fair Work Act volume runs to
    hundreds of thousands of characters and would not fit; a truncated
    provision can only *lose* support for a claim, so the cap fails in the
    closed direction, and the truncation is stated in the prompt so the judge
    does not treat an absence as a denial.
    """
    budget = settings().verify_provision_max_chars
    blocks: list[str] = []
    for provision in provisions:
        text = provision.text
        suffix = ""
        if len(text) > budget:
            text = text[:budget]
            suffix = "\n[TRUNCATED - this provision continues beyond what is shown]"
        blocks.append(
            f'<provision id="{provision_id_of(provision)}">\n'
            f"citation: {provision.pinpoint()}\n"
            f"heading: {provision.heading}\n"
            f"text:\n{text}{suffix}\n"
            f"</provision>"
        )
    claim_lines = "\n".join(f"{c.claim_id} ({c.unit}): {c.text}" for c in claims)
    return (
        f"{JUDGE_INSTRUCTIONS}\n\n"
        f"PROVISIONS ({len(provisions)}):\n" + "\n\n".join(blocks) + "\n\n"
        f"CLAIMS ({len(claims)}):\n{claim_lines}\n"
    )


def judge_family(model: str) -> str:
    """The provider prefix of an OpenRouter model id - "anthropic", "deepseek"."""
    return model.split("/", 1)[0].strip().lower()


def check_judge_model(judge_model: str, drafting_model: str) -> None:
    """Refuse a judge from the drafting model's own family.

    A model is a poor auditor of its own output: it reproduces the same
    training-data recollection that produced the claim, and confirms it. The
    requirement that these differ is therefore enforced here rather than left
    to whoever edits .env, and a violation fails closed like any other judge
    failure.
    """
    if not judge_model.strip():
        raise JudgeError("VERIFY_JUDGE_MODEL is not set")
    if judge_family(judge_model) == judge_family(drafting_model):
        raise JudgeError(
            f"the judge model {judge_model!r} is from the same family as the drafting "
            f"model {drafting_model!r}; verification requires a different family, so "
            f"set VERIFY_JUDGE_MODEL to a model from another provider"
        )


def openrouter_judge(prompt: str) -> tuple[str, JudgeCall]:
    """Ask the configured judge. The only place this module reaches the network."""
    config = settings()
    check_judge_model(config.verify_judge_model, config.model)
    if not config.openrouter_api_key:
        raise JudgeError("OPENROUTER_API_KEY is not set, so the draft cannot be verified")

    started = time.monotonic()
    try:
        response = httpx.post(
            f"{config.openrouter_base_url.rstrip('/')}/chat/completions",
            headers={"Authorization": f"Bearer {config.openrouter_api_key}"},
            json={
                "model": config.verify_judge_model,
                "messages": [{"role": "user", "content": prompt}],
                # Determinism where the provider offers it: two runs over one
                # draft should not disagree about whether a clause is invented.
                "temperature": 0,
                "response_format": {"type": "json_object"},
                "usage": {"include": True},
            },
            timeout=config.verify_judge_timeout,
        )
    except httpx.HTTPError as exc:
        raise JudgeError(f"judge unreachable: {exc}") from exc
    seconds = time.monotonic() - started

    if response.status_code != 200:
        raise JudgeError(f"judge returned HTTP {response.status_code}: {response.text[:300]}")
    try:
        payload = response.json()
        content = payload["choices"][0]["message"]["content"]
    except (ValueError, KeyError, IndexError, TypeError) as exc:
        raise JudgeError(f"judge response had no message content: {exc}") from exc

    usage = payload.get("usage") or {}
    return str(content), JudgeCall(
        model=config.verify_judge_model,
        seconds=seconds,
        prompt_tokens=int(usage.get("prompt_tokens") or 0),
        completion_tokens=int(usage.get("completion_tokens") or 0),
        cost_usd=float(usage["cost"]) if usage.get("cost") is not None else None,
    )


# --- step 3: validate the judge's answer (code) ----------------------------

_FENCE = re.compile(r"^\s*```(?:json)?\s*|\s*```\s*$")


def _parse(raw: str) -> list[dict[str, Any]]:
    """The judge's verdict objects, or a :class:`JudgeError`."""
    text = _FENCE.sub("", (raw or "").strip())
    try:
        payload = json.loads(text)
    except ValueError as exc:
        raise JudgeError(f"judge did not return JSON: {exc}") from exc
    if isinstance(payload, dict):
        payload = payload.get("verdicts") or payload.get("claims")
    if not isinstance(payload, list):
        raise JudgeError("judge JSON had no 'verdicts' list")
    return [item for item in payload if isinstance(item, dict)]


def _ids(value: Any) -> tuple[str, ...]:
    """Normalise whatever the judge put in provision_ids to a tuple of strings."""
    if value is None:
        return ()
    if isinstance(value, str | int):
        value = [value]
    if not isinstance(value, list):
        return ()
    return tuple(str(item).strip() for item in value if str(item).strip())


def unsupported(claim_id: str, reason: str) -> Ruling:
    """The verdict every failure resolves to."""
    return Ruling(claim_id=claim_id, verdict="UNSUPPORTED", provision_ids=(), reason=reason)


def validate_verdicts(
    raw: str,
    *,
    claims: Sequence[Claim],
    retrieved_ids: Iterable[str],
) -> tuple[Ruling, ...]:
    """Turn the judge's raw output into one validated ruling per claim.

    Every rule here is a way of saying the same thing: a verdict is only worth
    something if it can be checked. A claim the judge did not answer, answered
    with a word that is not a verdict, or supported by an id that retrieval
    never returned, has not been verified - so it is UNSUPPORTED. Note the
    direction: an id outside the retrieved set condemns the whole claim rather
    than being dropped from its list, because a judge that cites a provision it
    was not given is reasoning from something other than the evidence, and
    nothing it said about that claim can be trusted.
    """
    known = {str(i) for i in retrieved_ids}
    try:
        items = _parse(raw)
    except JudgeError as exc:
        return tuple(unsupported(c.claim_id, str(exc)) for c in claims)

    by_id: dict[str, dict[str, Any]] = {}
    for item in items:
        claim_id = str(item.get("claim_id", "")).strip()
        if claim_id and claim_id not in by_id:
            by_id[claim_id] = item

    rulings: list[Ruling] = []
    for claim in claims:
        answer = by_id.get(claim.claim_id)
        if answer is None:
            rulings.append(unsupported(claim.claim_id, "the judge returned no verdict for it"))
            continue

        verdict = str(answer.get("verdict", "")).strip()
        if verdict not in VERDICTS:
            rulings.append(
                unsupported(claim.claim_id, f"the judge returned no usable verdict ({verdict!r})")
            )
            continue

        reason = str(answer.get("reason", "")).strip() or "the judge gave no reason"
        ids = _ids(answer.get("provision_ids"))
        unknown = [i for i in ids if i not in known]
        if unknown:
            rulings.append(
                unsupported(
                    claim.claim_id,
                    "the judge cited "
                    + ", ".join(repr(i) for i in unknown)
                    + ", which retrieval did not return, so its reasoning was not "
                    "confined to the retrieved provisions",
                )
            )
            continue
        if verdict != "UNSUPPORTED" and not ids:
            rulings.append(
                unsupported(
                    claim.claim_id,
                    f"the judge answered {verdict} without naming a provision",
                )
            )
            continue

        rulings.append(
            Ruling(claim_id=claim.claim_id, verdict=verdict, provision_ids=ids, reason=reason)
        )
    return tuple(rulings)


# --- the whole thing -------------------------------------------------------


def verify_draft(
    draft_text: str,
    *,
    provisions: Sequence[RetrievedProvision],
    judge: JudgeFn | None = None,
    unit: ClaimUnit = SENTENCE,
) -> Verification:
    """Check every claim in ``draft_text`` against ``provisions`` and nothing else.

    Never raises. Every failure - no provisions, an unreachable judge, a
    same-family judge, unparseable JSON - comes back as UNSUPPORTED rulings
    carrying the reason, because a draft that could not be verified must not
    read as a draft that passed.
    """
    claims, skipped = split_claims(draft_text, unit=unit)
    try:
        judge_model = settings().verify_judge_model
    except ConfigError as exc:  # pragma: no cover - settings() is resolved by now
        judge_model = "(unconfigured)"
        return Verification(
            claims=claims,
            rulings=tuple(unsupported(c.claim_id, str(exc)) for c in claims),
            judge_model=judge_model,
            skipped_unsupplied=skipped,
        )

    if not claims:
        # The no-template outline lands here: it is scaffolding and
        # placeholders by design, and holds no drafted prose to check. Said
        # out loud, because "0 claims checked" with no explanation reads as
        # verification having failed rather than having had nothing to do.
        return Verification(
            claims=(),
            rulings=(),
            judge_model=judge_model,
            skipped_unsupplied=skipped,
            notes=(
                "This draft contains no verifiable claim: every line of it is a "
                "heading, a label, generated scaffolding, or a value not supplied.",
            ),
        )

    if not provisions:
        # No evidence exists, so no claim can be supported. Deterministic, and
        # it spends nothing: asking a judge to rule against an empty corpus
        # buys a round trip to reach the answer already known here.
        return Verification(
            claims=claims,
            rulings=tuple(
                unsupported(c.claim_id, "no provisions were retrieved, so nothing supports it")
                for c in claims
            ),
            judge_model=judge_model,
            skipped_unsupplied=skipped,
            notes=("Retrieval returned no provisions; every claim is unsupported by definition.",),
        )

    call: JudgeCall | None = None
    try:
        raw, call = (judge or openrouter_judge)(build_prompt(claims, provisions))
    except JudgeError as exc:
        return Verification(
            claims=claims,
            rulings=tuple(
                unsupported(c.claim_id, f"verification failed closed: {exc}") for c in claims
            ),
            judge_model=judge_model,
            skipped_unsupplied=skipped,
            call=JudgeCall(model=judge_model, seconds=0.0, error=str(exc)),
            notes=(f"The judge could not be used: {exc}",),
        )

    rulings = validate_verdicts(
        raw, claims=claims, retrieved_ids=[provision_id_of(p) for p in provisions]
    )
    return Verification(
        claims=claims,
        rulings=rulings,
        judge_model=call.model or judge_model,
        skipped_unsupplied=skipped,
        call=call,
    )


# --- output: mark, list, and report ----------------------------------------

VERIFICATION_NOTICE = (
    "Verification is automated. It checks each claim above against the text of "
    "the provisions retrieved for this draft and nothing else. It does not "
    "replace review by an admitted Australian legal practitioner, and a claim "
    "marked SUPPORTED has been matched to a provision, not approved."
)


def annotate(draft_text: str, verification: Verification) -> str:
    """Mark every flagged claim inline. Insertion only - nothing is removed.

    Markers are written back at the offsets recorded during the split, in
    reverse order so an earlier insertion cannot move a later one. The marker
    carries the claim id alone; the reason is long and belongs in OPEN ITEMS,
    where a practitioner reads it, rather than wedged into a contract clause.
    """
    flagged = {r.claim_id: r for r in verification.flagged}
    edits = sorted(
        (
            (claim.end, f" [{flagged[claim.claim_id].verdict}: {claim.claim_id}]")
            for claim in verification.claims
            if claim.claim_id in flagged
        ),
        reverse=True,
    )
    out = draft_text
    for at, marker in edits:
        out = out[:at] + marker + out[at:]
    return out


def open_items(verification: Verification) -> tuple[str, ...]:
    """One line per flagged claim, with its reason, for the OPEN ITEMS block."""
    lines: list[str] = []
    for ruling in verification.flagged:
        claim = verification.claim(ruling.claim_id)
        quoted = (claim.text if claim else "").strip()
        if len(quoted) > 160:
            quoted = quoted[:157].rstrip() + "..."
        lines.append(f'[{ruling.verdict}: {ruling.claim_id}] "{quoted}" - {ruling.reason}')
    return tuple(lines)


def section(verification: Verification) -> str:
    """The VERIFICATION block: what was checked, by what, and how it came out."""
    counts = verification.counts
    lines = [
        "## VERIFICATION",
        "",
        f"- Claims checked: {len(verification.claims)}",
        f"- SUPPORTED: {counts['SUPPORTED']}",
        f"- PARTIAL: {counts['PARTIAL']}",
        f"- UNSUPPORTED: {counts['UNSUPPORTED']}",
        f"- Not checked (value not supplied, see OPEN ITEMS): {verification.skipped_unsupplied}",
        f"- Judge model: {verification.judge_model}",
    ]
    lines += [f"- {note}" for note in verification.notes]
    lines += ["", VERIFICATION_NOTICE]
    return "\n".join(lines)


def annotate_draft(draft: Draft, verification: Verification) -> Draft:
    """Fold a verification into a draft: markers inline, reasons in OPEN ITEMS.

    Returns a new :class:`~michael.draft.Draft`. The body is only ever added
    to, and ``open_items`` - the ``[MISSING]`` list the acceptance suite is
    written against - is left exactly as it was; verification adds its own
    lines below it.
    """
    return replace(
        draft,
        body=annotate(draft.body, verification),
        verification_section=section(verification),
        verification_items=open_items(verification),
    )
