"""Render hermes/config.yaml and hermes/hermes.env from the project's .env.

Both outputs carry secrets and are git-ignored; the template beside them is not.
Run from the project root after changing .env:

    uv run python hermes/render_config.py
"""

from __future__ import annotations

import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
HERMES = ROOT / "hermes"


def env_values() -> dict[str, str]:
    text = (ROOT / ".env").read_text(encoding="utf-8")
    values: dict[str, str] = {}
    for line in text.splitlines():
        if "=" in line and not line.lstrip().startswith("#"):
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip()
    return values


def main() -> int:
    env = env_values()
    if not env.get("OPENROUTER_API_KEY"):
        print("OPENROUTER_API_KEY is empty in .env", file=sys.stderr)
        return 1

    # The container reaches Postgres over the michael_default Docker network,
    # not the host loopback the CLI uses.
    def containerised(url: str) -> str:
        return url.replace("127.0.0.1:5433", "michael-postgres:5432")

    substitutions = {
        "EMBEDDING_API_KEY": env.get("EMBEDDING_API_KEY", ""),
        "MICHAEL_DATABASE_URL": containerised(env.get("MICHAEL_DATABASE_URL", "")),
        "MICHAEL_RO_DATABASE_URL": containerised(env.get("MICHAEL_RO_DATABASE_URL", "")),
    }

    template = (HERMES / "config.template.yaml").read_text(encoding="utf-8")
    body = template.split("\n", 3)[3] if template.startswith("# TEMPLATE") else template
    for key, value in substitutions.items():
        body = body.replace("${" + key + "}", value)
    left = re.findall(r"\$\{(\w+)\}", body)
    if left:
        print(f"unsubstituted placeholders: {sorted(set(left))}", file=sys.stderr)
        return 1
    (HERMES / "config.yaml").write_text(body, encoding="utf-8")

    lines = [
        "# Generated by hermes/render_config.py from ../.env. Never committed.",
        f"OPENROUTER_API_KEY={env['OPENROUTER_API_KEY']}",
        "LLM_MODEL=anthropic/claude-opus-5",
    ]
    (HERMES / "hermes.env").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # SOUL.md is a derived artifact: a byte-identical copy of MICHAEL.md, which
    # is the single source of truth. Copying it here means the persona cannot
    # drift from the prompt when MICHAEL.md changes.
    source = (ROOT / "MICHAEL.md").read_bytes()
    (HERMES / "SOUL.md").write_bytes(source)
    digest = hashlib.sha256(source).hexdigest()

    print("rendered hermes/config.yaml and hermes/hermes.env")
    print(f"copied MICHAEL.md -> hermes/SOUL.md (sha256 {digest[:16]}...)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
